from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_authorizations_functions_function_id_versions_function_version_id.get import ApiForget
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_authorizations_functions_function_id_versions_function_version_id.post import ApiForpost
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_authorizations_functions_function_id_versions_function_version_id.delete import ApiFordelete


class V2NvcfAuthorizationsFunctionsFunctionIdVersionsFunctionVersionId(
    ApiForget,
    ApiForpost,
    ApiFordelete,
):
    pass
