from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_deployments_functions_function_id_versions_function_version_id.get import ApiForget
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_deployments_functions_function_id_versions_function_version_id.put import ApiForput
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_deployments_functions_function_id_versions_function_version_id.post import ApiForpost
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_deployments_functions_function_id_versions_function_version_id.delete import ApiFordelete


class V2NvcfDeploymentsFunctionsFunctionIdVersionsFunctionVersionId(
    ApiForget,
    ApiForput,
    ApiForpost,
    ApiFordelete,
):
    pass
