# coding: utf-8

"""
    Cloud Functions

    Since its founding in 1993, NVIDIA (NASDAQ: NVDA) has been a pioneer in accelerated computing. The company's invention of the GPU in 1999 sparked the growth of the PC gaming market, redefined computer graphics, ignited the era of modern AI and is fueling the creation of the metaverse. NVIDIA is now a full-stack computing company with data-center-scale offerings that are reshaping industry.

    The version of the OpenAPI document: 2.87.3
    Created by: https://www.nvidia.com/
"""

from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_assets.post import CreateAssetAndUrl
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_assets_asset_id.delete import DeleteAssetById
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_assets.get import ListAssets
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_assets_asset_id.get import ShowDetails
from nvidia_cloud_functions_python_sdk.apis.tags.asset_management_api_raw import AssetManagementApiRaw


class AssetManagementApi(
    CreateAssetAndUrl,
    DeleteAssetById,
    ListAssets,
    ShowDetails,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AssetManagementApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AssetManagementApiRaw(api_client)
