# coding: utf-8

"""
    Cloud Functions

    Since its founding in 1993, NVIDIA (NASDAQ: NVDA) has been a pioneer in accelerated computing. The company's invention of the GPU in 1999 sparked the growth of the PC gaming market, redefined computer graphics, ignited the era of modern AI and is fueling the creation of the metaverse. NVIDIA is now a full-stack computing company with data-center-scale offerings that are reshaping industry.

    The version of the OpenAPI document: 2.87.3
    Created by: https://www.nvidia.com/
"""

from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_authorizations_functions_function_id_add.patch import AddAccountToFunction
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_authorizations_functions_function_id_versions_function_version_id_add.patch import AddAccountToFunctionVersion
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_authorizations_functions_function_id_versions_function_version_id.post import AuthorizeFunctionAccounts
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_authorizations_functions_function_id.post import AuthorizeFunctionAccounts0
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_authorizations_functions_function_id.delete import DeleteAllExtraForFunction
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_authorizations_functions_function_id_versions_function_version_id.delete import DeleteExtraForFunctionVersion
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_authorizations_functions_function_id_versions_function_version_id.get import FunctionVersionAuthorizations
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_authorizations_functions_function_id.get import ListForFunction
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_authorizations_functions_function_id_remove.patch import RemoveFromFunctionAuthorization
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_authorizations_functions_function_id_versions_function_version_id_remove.patch import RemovePartyForVersion
from nvidia_cloud_functions_python_sdk.apis.tags.authorized_accounts_api_raw import AuthorizedAccountsApiRaw


class AuthorizedAccountsApi(
    AddAccountToFunction,
    AddAccountToFunctionVersion,
    AuthorizeFunctionAccounts,
    AuthorizeFunctionAccounts0,
    DeleteAllExtraForFunction,
    DeleteExtraForFunctionVersion,
    FunctionVersionAuthorizations,
    ListForFunction,
    RemoveFromFunctionAuthorization,
    RemovePartyForVersion,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AuthorizedAccountsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AuthorizedAccountsApiRaw(api_client)
