# coding: utf-8

"""
    Cloud Functions

    Since its founding in 1993, NVIDIA (NASDAQ: NVDA) has been a pioneer in accelerated computing. The company's invention of the GPU in 1999 sparked the growth of the PC gaming market, redefined computer graphics, ignited the era of modern AI and is fueling the creation of the metaverse. NVIDIA is now a full-stack computing company with data-center-scale offerings that are reshaping industry.

    The version of the OpenAPI document: 2.87.3
    Created by: https://www.nvidia.com/
"""

from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_authorizations_functions_function_id_add.patch import AddAccountToFunctionRaw
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_authorizations_functions_function_id_versions_function_version_id_add.patch import AddAccountToFunctionVersionRaw
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_authorizations_functions_function_id_versions_function_version_id.post import AuthorizeFunctionAccountsRaw
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_authorizations_functions_function_id.post import AuthorizeFunctionAccounts0Raw
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_authorizations_functions_function_id.delete import DeleteAllExtraForFunctionRaw
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_authorizations_functions_function_id_versions_function_version_id.delete import DeleteExtraForFunctionVersionRaw
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_authorizations_functions_function_id_versions_function_version_id.get import FunctionVersionAuthorizationsRaw
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_authorizations_functions_function_id.get import ListForFunctionRaw
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_authorizations_functions_function_id_remove.patch import RemoveFromFunctionAuthorizationRaw
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_authorizations_functions_function_id_versions_function_version_id_remove.patch import RemovePartyForVersionRaw


class AuthorizedAccountsApiRaw(
    AddAccountToFunctionRaw,
    AddAccountToFunctionVersionRaw,
    AuthorizeFunctionAccountsRaw,
    AuthorizeFunctionAccounts0Raw,
    DeleteAllExtraForFunctionRaw,
    DeleteExtraForFunctionVersionRaw,
    FunctionVersionAuthorizationsRaw,
    ListForFunctionRaw,
    RemoveFromFunctionAuthorizationRaw,
    RemovePartyForVersionRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
