# coding: utf-8

"""
    Cloud Functions

    Since its founding in 1993, NVIDIA (NASDAQ: NVDA) has been a pioneer in accelerated computing. The company's invention of the GPU in 1999 sparked the growth of the PC gaming market, redefined computer graphics, ignited the era of modern AI and is fueling the creation of the metaverse. NVIDIA is now a full-stack computing company with data-center-scale offerings that are reshaping industry.

    The version of the OpenAPI document: 2.87.3
    Created by: https://www.nvidia.com/
"""

from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_functions_function_id_versions.post import CreateFunctionVersion
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_functions_function_id_versions_function_version_id.delete import DeleteFunctionVersion
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_functions_function_id_versions_function_version_id.get import GetVersionDetails
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_functions_ids.get import ListFunctionIds
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_functions_function_id_versions.get import ListFunctionVersions
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_functions.get import ListFunctions
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_functions.post import RegisterNewFunction
from nvidia_cloud_functions_python_sdk.apis.tags.function_management_api_raw import FunctionManagementApiRaw


class FunctionManagementApi(
    CreateFunctionVersion,
    DeleteFunctionVersion,
    GetVersionDetails,
    ListFunctionIds,
    ListFunctionVersions,
    ListFunctions,
    RegisterNewFunction,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: FunctionManagementApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = FunctionManagementApiRaw(api_client)
