# coding: utf-8

"""
    Cloud Functions

    Since its founding in 1993, NVIDIA (NASDAQ: NVDA) has been a pioneer in accelerated computing. The company's invention of the GPU in 1999 sparked the growth of the PC gaming market, redefined computer graphics, ignited the era of modern AI and is fueling the creation of the metaverse. NVIDIA is now a full-stack computing company with data-center-scale offerings that are reshaping industry.

    The version of the OpenAPI document: 2.87.3
    Created by: https://www.nvidia.com/
"""

from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_functions_function_id_versions.post import CreateFunctionVersionRaw
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_functions_function_id_versions_function_version_id.delete import DeleteFunctionVersionRaw
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_functions_function_id_versions_function_version_id.get import GetVersionDetailsRaw
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_functions_ids.get import ListFunctionIdsRaw
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_functions_function_id_versions.get import ListFunctionVersionsRaw
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_functions.get import ListFunctionsRaw
from nvidia_cloud_functions_python_sdk.paths.v2_nvcf_functions.post import RegisterNewFunctionRaw


class FunctionManagementApiRaw(
    CreateFunctionVersionRaw,
    DeleteFunctionVersionRaw,
    GetVersionDetailsRaw,
    ListFunctionIdsRaw,
    ListFunctionVersionsRaw,
    ListFunctionsRaw,
    RegisterNewFunctionRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
