# coding: utf-8

"""
    Cloud Functions

    Since its founding in 1993, NVIDIA (NASDAQ: NVDA) has been a pioneer in accelerated computing. The company's invention of the GPU in 1999 sparked the growth of the PC gaming market, redefined computer graphics, ignited the era of modern AI and is fueling the creation of the metaverse. NVIDIA is now a full-stack computing company with data-center-scale offerings that are reshaping industry.

    The version of the OpenAPI document: 2.87.3
    Created by: https://www.nvidia.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from nvidia_cloud_functions_python_sdk import schemas  # noqa: F401


class CreateFunctionRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Request payload to create function.
    """


    class MetaOapg:
        required = {
            "inferenceUrl",
            "name",
        }
        
        class properties:
            
            
            class name(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 36
                    min_length = 10
                    regex=[{
                        'pattern': r'^[a-z0-9A-Z][a-z0-9A-Z\-_]*$',
                    }]
            inferenceUrl = schemas.StrSchema
            healthUri = schemas.StrSchema
            inferencePort = schemas.Int32Schema
            containerArgs = schemas.StrSchema
            
            
            class containerEnvironment(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['ContainerEnvironmentEntryDto']:
                        return ContainerEnvironmentEntryDto
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['ContainerEnvironmentEntryDto'], typing.List['ContainerEnvironmentEntryDto']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'containerEnvironment':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'ContainerEnvironmentEntryDto':
                    return super().__getitem__(i)
            
            
            class models(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    unique_items = True
                    
                    @staticmethod
                    def items() -> typing.Type['ArtifactDto']:
                        return ArtifactDto
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['ArtifactDto'], typing.List['ArtifactDto']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'models':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'ArtifactDto':
                    return super().__getitem__(i)
            containerImage = schemas.StrSchema
            helmChart = schemas.StrSchema
            helmChartServiceName = schemas.StrSchema
            
            
            class resources(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    unique_items = True
                    
                    @staticmethod
                    def items() -> typing.Type['ArtifactDto']:
                        return ArtifactDto
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['ArtifactDto'], typing.List['ArtifactDto']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'resources':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'ArtifactDto':
                    return super().__getitem__(i)
            
            
            class apiBodyFormat(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "PREDICT_V2": "PREDICT_V2",
                        "CUSTOM": "CUSTOM",
                    }
                
                @schemas.classproperty
                def PREDICT_V2(cls):
                    return cls("PREDICT_V2")
                
                @schemas.classproperty
                def CUSTOM(cls):
                    return cls("CUSTOM")
            __annotations__ = {
                "name": name,
                "inferenceUrl": inferenceUrl,
                "healthUri": healthUri,
                "inferencePort": inferencePort,
                "containerArgs": containerArgs,
                "containerEnvironment": containerEnvironment,
                "models": models,
                "containerImage": containerImage,
                "helmChart": helmChart,
                "helmChartServiceName": helmChartServiceName,
                "resources": resources,
                "apiBodyFormat": apiBodyFormat,
            }
    
    inferenceUrl: MetaOapg.properties.inferenceUrl
    name: MetaOapg.properties.name
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["inferenceUrl"]) -> MetaOapg.properties.inferenceUrl: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["healthUri"]) -> MetaOapg.properties.healthUri: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["inferencePort"]) -> MetaOapg.properties.inferencePort: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["containerArgs"]) -> MetaOapg.properties.containerArgs: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["containerEnvironment"]) -> MetaOapg.properties.containerEnvironment: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["models"]) -> MetaOapg.properties.models: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["containerImage"]) -> MetaOapg.properties.containerImage: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["helmChart"]) -> MetaOapg.properties.helmChart: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["helmChartServiceName"]) -> MetaOapg.properties.helmChartServiceName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["resources"]) -> MetaOapg.properties.resources: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["apiBodyFormat"]) -> MetaOapg.properties.apiBodyFormat: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["name", "inferenceUrl", "healthUri", "inferencePort", "containerArgs", "containerEnvironment", "models", "containerImage", "helmChart", "helmChartServiceName", "resources", "apiBodyFormat", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["inferenceUrl"]) -> MetaOapg.properties.inferenceUrl: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["healthUri"]) -> typing.Union[MetaOapg.properties.healthUri, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["inferencePort"]) -> typing.Union[MetaOapg.properties.inferencePort, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["containerArgs"]) -> typing.Union[MetaOapg.properties.containerArgs, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["containerEnvironment"]) -> typing.Union[MetaOapg.properties.containerEnvironment, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["models"]) -> typing.Union[MetaOapg.properties.models, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["containerImage"]) -> typing.Union[MetaOapg.properties.containerImage, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["helmChart"]) -> typing.Union[MetaOapg.properties.helmChart, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["helmChartServiceName"]) -> typing.Union[MetaOapg.properties.helmChartServiceName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["resources"]) -> typing.Union[MetaOapg.properties.resources, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["apiBodyFormat"]) -> typing.Union[MetaOapg.properties.apiBodyFormat, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["name", "inferenceUrl", "healthUri", "inferencePort", "containerArgs", "containerEnvironment", "models", "containerImage", "helmChart", "helmChartServiceName", "resources", "apiBodyFormat", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        inferenceUrl: typing.Union[MetaOapg.properties.inferenceUrl, str, ],
        name: typing.Union[MetaOapg.properties.name, str, ],
        healthUri: typing.Union[MetaOapg.properties.healthUri, str, schemas.Unset] = schemas.unset,
        inferencePort: typing.Union[MetaOapg.properties.inferencePort, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        containerArgs: typing.Union[MetaOapg.properties.containerArgs, str, schemas.Unset] = schemas.unset,
        containerEnvironment: typing.Union[MetaOapg.properties.containerEnvironment, list, tuple, schemas.Unset] = schemas.unset,
        models: typing.Union[MetaOapg.properties.models, list, tuple, schemas.Unset] = schemas.unset,
        containerImage: typing.Union[MetaOapg.properties.containerImage, str, schemas.Unset] = schemas.unset,
        helmChart: typing.Union[MetaOapg.properties.helmChart, str, schemas.Unset] = schemas.unset,
        helmChartServiceName: typing.Union[MetaOapg.properties.helmChartServiceName, str, schemas.Unset] = schemas.unset,
        resources: typing.Union[MetaOapg.properties.resources, list, tuple, schemas.Unset] = schemas.unset,
        apiBodyFormat: typing.Union[MetaOapg.properties.apiBodyFormat, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CreateFunctionRequest':
        return super().__new__(
            cls,
            *args,
            inferenceUrl=inferenceUrl,
            name=name,
            healthUri=healthUri,
            inferencePort=inferencePort,
            containerArgs=containerArgs,
            containerEnvironment=containerEnvironment,
            models=models,
            containerImage=containerImage,
            helmChart=helmChart,
            helmChartServiceName=helmChartServiceName,
            resources=resources,
            apiBodyFormat=apiBodyFormat,
            _configuration=_configuration,
            **kwargs,
        )

from nvidia_cloud_functions_python_sdk.model.artifact_dto import ArtifactDto
from nvidia_cloud_functions_python_sdk.model.container_environment_entry_dto import ContainerEnvironmentEntryDto
