# coding: utf-8

"""
    Cloud Functions

    Since its founding in 1993, NVIDIA (NASDAQ: NVDA) has been a pioneer in accelerated computing. The company's invention of the GPU in 1999 sparked the growth of the PC gaming market, redefined computer graphics, ignited the era of modern AI and is fueling the creation of the metaverse. NVIDIA is now a full-stack computing company with data-center-scale offerings that are reshaping industry.

    The version of the OpenAPI document: 2.87.3
    Created by: https://www.nvidia.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from nvidia_cloud_functions_python_sdk import schemas  # noqa: F401


class FunctionDeploymentRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Request to deploy a function
    """


    class MetaOapg:
        required = {
            "deploymentSpecifications",
        }
        
        class properties:
            
            
            class deploymentSpecifications(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['GpuSpecificationDto']:
                        return GpuSpecificationDto
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['GpuSpecificationDto'], typing.List['GpuSpecificationDto']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'deploymentSpecifications':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'GpuSpecificationDto':
                    return super().__getitem__(i)
            __annotations__ = {
                "deploymentSpecifications": deploymentSpecifications,
            }
    
    deploymentSpecifications: MetaOapg.properties.deploymentSpecifications
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["deploymentSpecifications"]) -> MetaOapg.properties.deploymentSpecifications: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["deploymentSpecifications", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["deploymentSpecifications"]) -> MetaOapg.properties.deploymentSpecifications: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["deploymentSpecifications", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        deploymentSpecifications: typing.Union[MetaOapg.properties.deploymentSpecifications, list, tuple, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'FunctionDeploymentRequest':
        return super().__new__(
            cls,
            *args,
            deploymentSpecifications=deploymentSpecifications,
            _configuration=_configuration,
            **kwargs,
        )

from nvidia_cloud_functions_python_sdk.model.gpu_specification_dto import GpuSpecificationDto
