# coding: utf-8

"""
    Cloud Functions

    Since its founding in 1993, NVIDIA (NASDAQ: NVDA) has been a pioneer in accelerated computing. The company's invention of the GPU in 1999 sparked the growth of the PC gaming market, redefined computer graphics, ignited the era of modern AI and is fueling the creation of the metaverse. NVIDIA is now a full-stack computing company with data-center-scale offerings that are reshaping industry.

    The version of the OpenAPI document: 2.87.3
    Created by: https://www.nvidia.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from nvidia_cloud_functions_python_sdk import schemas  # noqa: F401


class FunctionDto(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Data Transfer Object(DTO) representing a function
    """


    class MetaOapg:
        required = {
            "createdAt",
            "versionId",
            "name",
            "id",
            "ncaId",
            "healthUri",
            "status",
        }
        
        class properties:
            id = schemas.UUIDSchema
            ncaId = schemas.StrSchema
            versionId = schemas.UUIDSchema
            name = schemas.StrSchema
            
            
            class status(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "ACTIVE": "ACTIVE",
                        "DEPLOYING": "DEPLOYING",
                        "ERROR": "ERROR",
                        "INACTIVE": "INACTIVE",
                        "DELETED": "DELETED",
                    }
                
                @schemas.classproperty
                def ACTIVE(cls):
                    return cls("ACTIVE")
                
                @schemas.classproperty
                def DEPLOYING(cls):
                    return cls("DEPLOYING")
                
                @schemas.classproperty
                def ERROR(cls):
                    return cls("ERROR")
                
                @schemas.classproperty
                def INACTIVE(cls):
                    return cls("INACTIVE")
                
                @schemas.classproperty
                def DELETED(cls):
                    return cls("DELETED")
            healthUri = schemas.StrSchema
            createdAt = schemas.DateTimeSchema
            inferenceUrl = schemas.StrSchema
            ownedByDifferentAccount = schemas.BoolSchema
            inferencePort = schemas.Int32Schema
            containerArgs = schemas.StrSchema
            
            
            class containerEnvironment(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['ContainerEnvironmentEntryDto']:
                        return ContainerEnvironmentEntryDto
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['ContainerEnvironmentEntryDto'], typing.List['ContainerEnvironmentEntryDto']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'containerEnvironment':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'ContainerEnvironmentEntryDto':
                    return super().__getitem__(i)
            
            
            class models(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    unique_items = True
                    
                    @staticmethod
                    def items() -> typing.Type['ArtifactDto']:
                        return ArtifactDto
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['ArtifactDto'], typing.List['ArtifactDto']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'models':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'ArtifactDto':
                    return super().__getitem__(i)
            containerImage = schemas.StrSchema
            
            
            class apiBodyFormat(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "PREDICT_V2": "PREDICT_V2",
                        "CUSTOM": "CUSTOM",
                    }
                
                @schemas.classproperty
                def PREDICT_V2(cls):
                    return cls("PREDICT_V2")
                
                @schemas.classproperty
                def CUSTOM(cls):
                    return cls("CUSTOM")
            helmChart = schemas.StrSchema
            helmChartServiceName = schemas.StrSchema
            
            
            class activeInstances(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['InstanceDto']:
                        return InstanceDto
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['InstanceDto'], typing.List['InstanceDto']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'activeInstances':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'InstanceDto':
                    return super().__getitem__(i)
            
            
            class resources(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    unique_items = True
                    
                    @staticmethod
                    def items() -> typing.Type['ArtifactDto']:
                        return ArtifactDto
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['ArtifactDto'], typing.List['ArtifactDto']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'resources':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'ArtifactDto':
                    return super().__getitem__(i)
            __annotations__ = {
                "id": id,
                "ncaId": ncaId,
                "versionId": versionId,
                "name": name,
                "status": status,
                "healthUri": healthUri,
                "createdAt": createdAt,
                "inferenceUrl": inferenceUrl,
                "ownedByDifferentAccount": ownedByDifferentAccount,
                "inferencePort": inferencePort,
                "containerArgs": containerArgs,
                "containerEnvironment": containerEnvironment,
                "models": models,
                "containerImage": containerImage,
                "apiBodyFormat": apiBodyFormat,
                "helmChart": helmChart,
                "helmChartServiceName": helmChartServiceName,
                "activeInstances": activeInstances,
                "resources": resources,
            }
    
    createdAt: MetaOapg.properties.createdAt
    versionId: MetaOapg.properties.versionId
    name: MetaOapg.properties.name
    id: MetaOapg.properties.id
    ncaId: MetaOapg.properties.ncaId
    healthUri: MetaOapg.properties.healthUri
    status: MetaOapg.properties.status
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ncaId"]) -> MetaOapg.properties.ncaId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["versionId"]) -> MetaOapg.properties.versionId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["healthUri"]) -> MetaOapg.properties.healthUri: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["createdAt"]) -> MetaOapg.properties.createdAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["inferenceUrl"]) -> MetaOapg.properties.inferenceUrl: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ownedByDifferentAccount"]) -> MetaOapg.properties.ownedByDifferentAccount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["inferencePort"]) -> MetaOapg.properties.inferencePort: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["containerArgs"]) -> MetaOapg.properties.containerArgs: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["containerEnvironment"]) -> MetaOapg.properties.containerEnvironment: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["models"]) -> MetaOapg.properties.models: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["containerImage"]) -> MetaOapg.properties.containerImage: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["apiBodyFormat"]) -> MetaOapg.properties.apiBodyFormat: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["helmChart"]) -> MetaOapg.properties.helmChart: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["helmChartServiceName"]) -> MetaOapg.properties.helmChartServiceName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["activeInstances"]) -> MetaOapg.properties.activeInstances: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["resources"]) -> MetaOapg.properties.resources: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["id", "ncaId", "versionId", "name", "status", "healthUri", "createdAt", "inferenceUrl", "ownedByDifferentAccount", "inferencePort", "containerArgs", "containerEnvironment", "models", "containerImage", "apiBodyFormat", "helmChart", "helmChartServiceName", "activeInstances", "resources", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ncaId"]) -> MetaOapg.properties.ncaId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["versionId"]) -> MetaOapg.properties.versionId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["healthUri"]) -> MetaOapg.properties.healthUri: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["createdAt"]) -> MetaOapg.properties.createdAt: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["inferenceUrl"]) -> typing.Union[MetaOapg.properties.inferenceUrl, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ownedByDifferentAccount"]) -> typing.Union[MetaOapg.properties.ownedByDifferentAccount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["inferencePort"]) -> typing.Union[MetaOapg.properties.inferencePort, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["containerArgs"]) -> typing.Union[MetaOapg.properties.containerArgs, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["containerEnvironment"]) -> typing.Union[MetaOapg.properties.containerEnvironment, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["models"]) -> typing.Union[MetaOapg.properties.models, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["containerImage"]) -> typing.Union[MetaOapg.properties.containerImage, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["apiBodyFormat"]) -> typing.Union[MetaOapg.properties.apiBodyFormat, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["helmChart"]) -> typing.Union[MetaOapg.properties.helmChart, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["helmChartServiceName"]) -> typing.Union[MetaOapg.properties.helmChartServiceName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["activeInstances"]) -> typing.Union[MetaOapg.properties.activeInstances, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["resources"]) -> typing.Union[MetaOapg.properties.resources, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["id", "ncaId", "versionId", "name", "status", "healthUri", "createdAt", "inferenceUrl", "ownedByDifferentAccount", "inferencePort", "containerArgs", "containerEnvironment", "models", "containerImage", "apiBodyFormat", "helmChart", "helmChartServiceName", "activeInstances", "resources", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        createdAt: typing.Union[MetaOapg.properties.createdAt, str, datetime, ],
        versionId: typing.Union[MetaOapg.properties.versionId, str, uuid.UUID, ],
        name: typing.Union[MetaOapg.properties.name, str, ],
        id: typing.Union[MetaOapg.properties.id, str, uuid.UUID, ],
        ncaId: typing.Union[MetaOapg.properties.ncaId, str, ],
        healthUri: typing.Union[MetaOapg.properties.healthUri, str, ],
        status: typing.Union[MetaOapg.properties.status, str, ],
        inferenceUrl: typing.Union[MetaOapg.properties.inferenceUrl, str, schemas.Unset] = schemas.unset,
        ownedByDifferentAccount: typing.Union[MetaOapg.properties.ownedByDifferentAccount, bool, schemas.Unset] = schemas.unset,
        inferencePort: typing.Union[MetaOapg.properties.inferencePort, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        containerArgs: typing.Union[MetaOapg.properties.containerArgs, str, schemas.Unset] = schemas.unset,
        containerEnvironment: typing.Union[MetaOapg.properties.containerEnvironment, list, tuple, schemas.Unset] = schemas.unset,
        models: typing.Union[MetaOapg.properties.models, list, tuple, schemas.Unset] = schemas.unset,
        containerImage: typing.Union[MetaOapg.properties.containerImage, str, schemas.Unset] = schemas.unset,
        apiBodyFormat: typing.Union[MetaOapg.properties.apiBodyFormat, str, schemas.Unset] = schemas.unset,
        helmChart: typing.Union[MetaOapg.properties.helmChart, str, schemas.Unset] = schemas.unset,
        helmChartServiceName: typing.Union[MetaOapg.properties.helmChartServiceName, str, schemas.Unset] = schemas.unset,
        activeInstances: typing.Union[MetaOapg.properties.activeInstances, list, tuple, schemas.Unset] = schemas.unset,
        resources: typing.Union[MetaOapg.properties.resources, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'FunctionDto':
        return super().__new__(
            cls,
            *args,
            createdAt=createdAt,
            versionId=versionId,
            name=name,
            id=id,
            ncaId=ncaId,
            healthUri=healthUri,
            status=status,
            inferenceUrl=inferenceUrl,
            ownedByDifferentAccount=ownedByDifferentAccount,
            inferencePort=inferencePort,
            containerArgs=containerArgs,
            containerEnvironment=containerEnvironment,
            models=models,
            containerImage=containerImage,
            apiBodyFormat=apiBodyFormat,
            helmChart=helmChart,
            helmChartServiceName=helmChartServiceName,
            activeInstances=activeInstances,
            resources=resources,
            _configuration=_configuration,
            **kwargs,
        )

from nvidia_cloud_functions_python_sdk.model.artifact_dto import ArtifactDto
from nvidia_cloud_functions_python_sdk.model.container_environment_entry_dto import ContainerEnvironmentEntryDto
from nvidia_cloud_functions_python_sdk.model.instance_dto import InstanceDto
