# coding: utf-8

"""
    Cloud Functions

    Since its founding in 1993, NVIDIA (NASDAQ: NVDA) has been a pioneer in accelerated computing. The company's invention of the GPU in 1999 sparked the growth of the PC gaming market, redefined computer graphics, ignited the era of modern AI and is fueling the creation of the metaverse. NVIDIA is now a full-stack computing company with data-center-scale offerings that are reshaping industry.

    The version of the OpenAPI document: 2.87.3
    Created by: https://www.nvidia.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from nvidia_cloud_functions_python_sdk import schemas  # noqa: F401


class GetPositionInQueueResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Request position in queue for invocation request
    """


    class MetaOapg:
        required = {
            "functionId",
            "functionVersionId",
        }
        
        class properties:
            functionVersionId = schemas.UUIDSchema
            functionId = schemas.UUIDSchema
            positionInQueue = schemas.Int32Schema
            __annotations__ = {
                "functionVersionId": functionVersionId,
                "functionId": functionId,
                "positionInQueue": positionInQueue,
            }
    
    functionId: MetaOapg.properties.functionId
    functionVersionId: MetaOapg.properties.functionVersionId
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["functionVersionId"]) -> MetaOapg.properties.functionVersionId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["functionId"]) -> MetaOapg.properties.functionId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["positionInQueue"]) -> MetaOapg.properties.positionInQueue: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["functionVersionId", "functionId", "positionInQueue", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["functionVersionId"]) -> MetaOapg.properties.functionVersionId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["functionId"]) -> MetaOapg.properties.functionId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["positionInQueue"]) -> typing.Union[MetaOapg.properties.positionInQueue, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["functionVersionId", "functionId", "positionInQueue", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        functionId: typing.Union[MetaOapg.properties.functionId, str, uuid.UUID, ],
        functionVersionId: typing.Union[MetaOapg.properties.functionVersionId, str, uuid.UUID, ],
        positionInQueue: typing.Union[MetaOapg.properties.positionInQueue, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'GetPositionInQueueResponse':
        return super().__new__(
            cls,
            *args,
            functionId=functionId,
            functionVersionId=functionVersionId,
            positionInQueue=positionInQueue,
            _configuration=_configuration,
            **kwargs,
        )
