# coding: utf-8

"""
    Cloud Functions

    Since its founding in 1993, NVIDIA (NASDAQ: NVDA) has been a pioneer in accelerated computing. The company's invention of the GPU in 1999 sparked the growth of the PC gaming market, redefined computer graphics, ignited the era of modern AI and is fueling the creation of the metaverse. NVIDIA is now a full-stack computing company with data-center-scale offerings that are reshaping industry.

    The version of the OpenAPI document: 2.87.3
    Created by: https://www.nvidia.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from nvidia_cloud_functions_python_sdk import schemas  # noqa: F401


class GpuSpecificationDto(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Data Transfer Object(DTO) representing GPU specification.
    """


    class MetaOapg:
        required = {
            "minInstances",
            "backend",
            "maxInstances",
            "gpu",
        }
        
        class properties:
            gpu = schemas.StrSchema
            backend = schemas.StrSchema
            maxInstances = schemas.Int32Schema
            minInstances = schemas.Int32Schema
            instanceType = schemas.StrSchema
        
            @staticmethod
            def availabilityZones() -> typing.Type['GpuSpecificationDtoAvailabilityZones']:
                return GpuSpecificationDtoAvailabilityZones
            
            
            class maxRequestConcurrency(
                schemas.Int32Schema
            ):
            
            
                class MetaOapg:
                    format = 'int32'
                    inclusive_maximum = 1024
                    inclusive_minimum = 1
            configuration = schemas.DictSchema
            __annotations__ = {
                "gpu": gpu,
                "backend": backend,
                "maxInstances": maxInstances,
                "minInstances": minInstances,
                "instanceType": instanceType,
                "availabilityZones": availabilityZones,
                "maxRequestConcurrency": maxRequestConcurrency,
                "configuration": configuration,
            }
    
    minInstances: MetaOapg.properties.minInstances
    backend: MetaOapg.properties.backend
    maxInstances: MetaOapg.properties.maxInstances
    gpu: MetaOapg.properties.gpu
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["gpu"]) -> MetaOapg.properties.gpu: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["backend"]) -> MetaOapg.properties.backend: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["maxInstances"]) -> MetaOapg.properties.maxInstances: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["minInstances"]) -> MetaOapg.properties.minInstances: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["instanceType"]) -> MetaOapg.properties.instanceType: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["availabilityZones"]) -> 'GpuSpecificationDtoAvailabilityZones': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["maxRequestConcurrency"]) -> MetaOapg.properties.maxRequestConcurrency: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["configuration"]) -> MetaOapg.properties.configuration: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["gpu", "backend", "maxInstances", "minInstances", "instanceType", "availabilityZones", "maxRequestConcurrency", "configuration", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["gpu"]) -> MetaOapg.properties.gpu: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["backend"]) -> MetaOapg.properties.backend: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["maxInstances"]) -> MetaOapg.properties.maxInstances: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["minInstances"]) -> MetaOapg.properties.minInstances: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["instanceType"]) -> typing.Union[MetaOapg.properties.instanceType, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["availabilityZones"]) -> typing.Union['GpuSpecificationDtoAvailabilityZones', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["maxRequestConcurrency"]) -> typing.Union[MetaOapg.properties.maxRequestConcurrency, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["configuration"]) -> typing.Union[MetaOapg.properties.configuration, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["gpu", "backend", "maxInstances", "minInstances", "instanceType", "availabilityZones", "maxRequestConcurrency", "configuration", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        minInstances: typing.Union[MetaOapg.properties.minInstances, decimal.Decimal, int, ],
        backend: typing.Union[MetaOapg.properties.backend, str, ],
        maxInstances: typing.Union[MetaOapg.properties.maxInstances, decimal.Decimal, int, ],
        gpu: typing.Union[MetaOapg.properties.gpu, str, ],
        instanceType: typing.Union[MetaOapg.properties.instanceType, str, schemas.Unset] = schemas.unset,
        availabilityZones: typing.Union['GpuSpecificationDtoAvailabilityZones', schemas.Unset] = schemas.unset,
        maxRequestConcurrency: typing.Union[MetaOapg.properties.maxRequestConcurrency, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        configuration: typing.Union[MetaOapg.properties.configuration, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'GpuSpecificationDto':
        return super().__new__(
            cls,
            *args,
            minInstances=minInstances,
            backend=backend,
            maxInstances=maxInstances,
            gpu=gpu,
            instanceType=instanceType,
            availabilityZones=availabilityZones,
            maxRequestConcurrency=maxRequestConcurrency,
            configuration=configuration,
            _configuration=_configuration,
            **kwargs,
        )

from nvidia_cloud_functions_python_sdk.model.gpu_specification_dto_availability_zones import GpuSpecificationDtoAvailabilityZones
