# coding: utf-8

"""
    Cloud Functions

    Since its founding in 1993, NVIDIA (NASDAQ: NVDA) has been a pioneer in accelerated computing. The company's invention of the GPU in 1999 sparked the growth of the PC gaming market, redefined computer graphics, ignited the era of modern AI and is fueling the creation of the metaverse. NVIDIA is now a full-stack computing company with data-center-scale offerings that are reshaping industry.

    The version of the OpenAPI document: 2.87.3
    Created by: https://www.nvidia.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from nvidia_cloud_functions_python_sdk import schemas  # noqa: F401


class QueueDto(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Data Transfer Object(DTO) representing a request queue for function version
    """


    class MetaOapg:
        required = {
            "functionName",
            "functionVersionId",
            "functionStatus",
        }
        
        class properties:
            functionVersionId = schemas.UUIDSchema
            functionName = schemas.StrSchema
            
            
            class functionStatus(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "ACTIVE": "ACTIVE",
                        "DEPLOYING": "DEPLOYING",
                        "ERROR": "ERROR",
                        "INACTIVE": "INACTIVE",
                        "DELETED": "DELETED",
                    }
                
                @schemas.classproperty
                def ACTIVE(cls):
                    return cls("ACTIVE")
                
                @schemas.classproperty
                def DEPLOYING(cls):
                    return cls("DEPLOYING")
                
                @schemas.classproperty
                def ERROR(cls):
                    return cls("ERROR")
                
                @schemas.classproperty
                def INACTIVE(cls):
                    return cls("INACTIVE")
                
                @schemas.classproperty
                def DELETED(cls):
                    return cls("DELETED")
            queueDepth = schemas.Int32Schema
            __annotations__ = {
                "functionVersionId": functionVersionId,
                "functionName": functionName,
                "functionStatus": functionStatus,
                "queueDepth": queueDepth,
            }
    
    functionName: MetaOapg.properties.functionName
    functionVersionId: MetaOapg.properties.functionVersionId
    functionStatus: MetaOapg.properties.functionStatus
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["functionVersionId"]) -> MetaOapg.properties.functionVersionId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["functionName"]) -> MetaOapg.properties.functionName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["functionStatus"]) -> MetaOapg.properties.functionStatus: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["queueDepth"]) -> MetaOapg.properties.queueDepth: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["functionVersionId", "functionName", "functionStatus", "queueDepth", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["functionVersionId"]) -> MetaOapg.properties.functionVersionId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["functionName"]) -> MetaOapg.properties.functionName: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["functionStatus"]) -> MetaOapg.properties.functionStatus: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["queueDepth"]) -> typing.Union[MetaOapg.properties.queueDepth, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["functionVersionId", "functionName", "functionStatus", "queueDepth", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        functionName: typing.Union[MetaOapg.properties.functionName, str, ],
        functionVersionId: typing.Union[MetaOapg.properties.functionVersionId, str, uuid.UUID, ],
        functionStatus: typing.Union[MetaOapg.properties.functionStatus, str, ],
        queueDepth: typing.Union[MetaOapg.properties.queueDepth, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'QueueDto':
        return super().__new__(
            cls,
            *args,
            functionName=functionName,
            functionVersionId=functionVersionId,
            functionStatus=functionStatus,
            queueDepth=queueDepth,
            _configuration=_configuration,
            **kwargs,
        )
