# coding: utf-8

"""
    Cloud Functions

    Since its founding in 1993, NVIDIA (NASDAQ: NVDA) has been a pioneer in accelerated computing. The company's invention of the GPU in 1999 sparked the growth of the PC gaming market, redefined computer graphics, ignited the era of modern AI and is fueling the creation of the metaverse. NVIDIA is now a full-stack computing company with data-center-scale offerings that are reshaping industry.

    The version of the OpenAPI document: 2.87.3
    Created by: https://www.nvidia.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from nvidia_cloud_functions_python_sdk import schemas  # noqa: F401


class RequestHeaderDto(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Data Transfer Object(DTO) representing header/address for Cloud Functions processing. 
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def inputAssetReferences() -> typing.Type['RequestHeaderDtoInputAssetReferences']:
                return RequestHeaderDtoInputAssetReferences
            
            
            class meteringData(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['MeteringDataEntryDto']:
                        return MeteringDataEntryDto
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['MeteringDataEntryDto'], typing.List['MeteringDataEntryDto']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'meteringData':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'MeteringDataEntryDto':
                    return super().__getitem__(i)
            
            
            class pollDurationSeconds(
                schemas.Int32Schema
            ):
                pass
            __annotations__ = {
                "inputAssetReferences": inputAssetReferences,
                "meteringData": meteringData,
                "pollDurationSeconds": pollDurationSeconds,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["inputAssetReferences"]) -> 'RequestHeaderDtoInputAssetReferences': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["meteringData"]) -> MetaOapg.properties.meteringData: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pollDurationSeconds"]) -> MetaOapg.properties.pollDurationSeconds: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["inputAssetReferences", "meteringData", "pollDurationSeconds", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["inputAssetReferences"]) -> typing.Union['RequestHeaderDtoInputAssetReferences', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["meteringData"]) -> typing.Union[MetaOapg.properties.meteringData, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pollDurationSeconds"]) -> typing.Union[MetaOapg.properties.pollDurationSeconds, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["inputAssetReferences", "meteringData", "pollDurationSeconds", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        inputAssetReferences: typing.Union['RequestHeaderDtoInputAssetReferences', schemas.Unset] = schemas.unset,
        meteringData: typing.Union[MetaOapg.properties.meteringData, list, tuple, schemas.Unset] = schemas.unset,
        pollDurationSeconds: typing.Union[MetaOapg.properties.pollDurationSeconds, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'RequestHeaderDto':
        return super().__new__(
            cls,
            *args,
            inputAssetReferences=inputAssetReferences,
            meteringData=meteringData,
            pollDurationSeconds=pollDurationSeconds,
            _configuration=_configuration,
            **kwargs,
        )

from nvidia_cloud_functions_python_sdk.model.metering_data_entry_dto import MeteringDataEntryDto
from nvidia_cloud_functions_python_sdk.model.request_header_dto_input_asset_references import RequestHeaderDtoInputAssetReferences
